/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payroll.view;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.dbconnection.DBConnection;
import lk.ijse.payroll.model.EmployeeDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Chamil
 */
public class AttendanceReport extends javax.swing.JFrame {
    private String employeeName;

    /**
     * Creates new form AttendanceReport
     */
    public AttendanceReport() {
        initComponents();
        loadEmployeeName();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TextFieldDateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabelEmployeeName = new javax.swing.JLabel();
        jComboBoxEmpName = new javax.swing.JComboBox<>();
        jLabelDesignation = new javax.swing.JLabel();
        TxtDesignation = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelDesignation1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        jLabelEmployeeID = new javax.swing.JLabel();
        TxtEmployeeId = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(TextFieldDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, 30));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        jPanel2.add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 30));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Date");
        jPanel2.add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        TxtDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDesignation.setForeground(new java.awt.Color(31, 58, 147));
        TxtDesignation.setBorder(null);
        TxtDesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDesignationKeyReleased(evt);
            }
        });
        jPanel2.add(TxtDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, 30));

        jSeparator16.setBackground(new java.awt.Color(0, 139, 139));
        jSeparator16.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator16.setOpaque(true);
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 190, -1));

        jLabelDesignation1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelDesignation1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation1.setText("Designation");
        jPanel2.add(jLabelDesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        jButton1.setText("Cancel");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 90, 30));

        BtnView.setText("View Report");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });
        jPanel2.add(BtnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        jPanel2.add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        TxtEmployeeId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEmployeeId.setForeground(new java.awt.Color(31, 58, 147));
        TxtEmployeeId.setBorder(null);
        TxtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmployeeIdActionPerformed(evt);
            }
        });
        jPanel2.add(TxtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 70, -1));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
                TxtEmployeeId.setText(employee.getId());
                TxtDesignation.setText(employee.getDesignation());

            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed

    private void TxtDesignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDesignationKeyReleased
        String txt = TxtDesignation.getText();
        int caretPosition = TxtDesignation.getCaretPosition();
        if (!txt.matches("^[A-Za-z//]*$")) {
            TxtDesignation.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtDesignation.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtDesignationKeyReleased

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        InputStream input=getClass().getResourceAsStream("/lk/ijse/payroll/report/AttendanceRepo.jasper");
       HashMap map=new HashMap();
       try {
            JasperPrint jasperPrint=JasperFillManager.fillReport(input, map,DBConnection.getInstance().getConnection());
            JasperViewer.viewReport(jasperPrint);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) { 
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnViewActionPerformed

    private void TxtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmployeeIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnView;
    private com.toedter.calendar.JDateChooser TextFieldDateOfBirth;
    private javax.swing.JTextField TxtDesignation;
    private javax.swing.JTextField TxtEmployeeId;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelDesignation1;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator22;
    // End of variables declaration//GEN-END:variables

    private void loadEmployeeName() {
        try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
