/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lk.ijse.payroll.view;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.payroll.common.IdGenerater;
import lk.ijse.payroll.controller.AllowanceController;
import lk.ijse.payroll.controller.DeductionController;
import lk.ijse.payroll.controller.EmployeeAttendanceController;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.controller.EmployeeSalaryController;
import lk.ijse.payroll.dbconnection.DBConnection;
import lk.ijse.payroll.entity.Allowance;
import lk.ijse.payroll.model.AllowanceDTO;
import lk.ijse.payroll.model.AttendanceDTO;
import lk.ijse.payroll.model.DeductionDTO;
import lk.ijse.payroll.model.EmployeeDTO;
import lk.ijse.payroll.model.SalaryDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shashika
 */
public class EmployeeSalary extends javax.swing.JPanel {
    private String employeeName ,selectDate;

    /** Creates new form EmployeeSalary */
    public EmployeeSalary() {
        initComponents();
        loadEmployeeName();
        genarateSalaryId();
        
        
        double salary  = Double.parseDouble(TxtBasicSalary.getText());
                double percentageEtf = 3,percentageEpf=8, percentageEpf2=12 ;
                
                double etf = (salary * percentageEtf)/100;
                double epf=(salary * percentageEpf )/100;
                double epf2= (salary * percentageEpf2 )/100;
                
                Txtepf.setText(""+epf);
                TxtETF.setText(""+etf);
                Txtepff.setText(""+epf2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmpAtt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelDesignation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jComboBoxEmpName = new javax.swing.JComboBox<>();
        jLabelBasicSalary = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelIncentivesAmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        TxtTotalAllowance = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TxtHouseAllowance = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TxtVehicleAllowance = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        TxtMedical = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelIncentivesAmount1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        TxtTotalDeducton = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        TxtInsurance = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        TxtWelfare = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        TxtEPF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        TxtNetSalary = new javax.swing.JTextField();
        jLabelAdd = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        TxtBasicSalary = new javax.swing.JTextField();
        DatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        jSeparator21 = new javax.swing.JSeparator();
        TxtDesignation = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        TxtEmployeeId = new javax.swing.JTextField();
        jLabelBasicSalary1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        TxtSalaryId = new javax.swing.JTextField();
        ButtonPaySlip = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        TxtOverTime = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        TxtGrossSalary = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        TxtLateHoursRate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        Txtepf = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        Txtepff = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        TxtETF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ButtonAdd1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpAtt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        jLabelEmpAtt.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmpAtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payroll/asset/icons8_Purchase_Order_30px_1.png"))); // NOI18N
        jLabelEmpAtt.setText(" Pay Slip");
        add(jLabelEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        jSeparator4.setBackground(new java.awt.Color(210, 215, 211));
        jSeparator4.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 20, -1, 40));

        jSeparator2.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1630, 10));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1630, -1));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Designation");
        add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 58, 147));
        jLabel1.setText("Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 50, 30));

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));

        jLabelBasicSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary.setText("Basic Salary");
        add(jLabelBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, 30));

        jSeparator3.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1760, 10));

        jLabelIncentivesAmount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelIncentivesAmount.setForeground(new java.awt.Color(31, 58, 147));
        jLabelIncentivesAmount.setText("Allowance Amount");
        add(jLabelIncentivesAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 220, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 58, 147));
        jLabel2.setText("Gross Salary");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 140, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 147));
        jLabel3.setText("House Rent Allowance");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 147));
        jLabel4.setText("Vehicle Allowance");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 147));
        jLabel7.setText("Medical");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 30));

        jSeparator11.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator11.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator11.setOpaque(true);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 170, -1));

        TxtTotalAllowance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtTotalAllowance.setForeground(new java.awt.Color(31, 58, 147));
        TxtTotalAllowance.setBorder(null);
        TxtTotalAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalAllowanceActionPerformed(evt);
            }
        });
        add(TxtTotalAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 170, 30));

        jSeparator6.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator6.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator6.setOpaque(true);
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 170, -1));

        TxtHouseAllowance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtHouseAllowance.setForeground(new java.awt.Color(31, 58, 147));
        TxtHouseAllowance.setBorder(null);
        TxtHouseAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHouseAllowanceActionPerformed(evt);
            }
        });
        add(TxtHouseAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, 30));

        jSeparator7.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator7.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator7.setOpaque(true);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 170, -1));

        TxtVehicleAllowance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtVehicleAllowance.setForeground(new java.awt.Color(31, 58, 147));
        TxtVehicleAllowance.setBorder(null);
        TxtVehicleAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVehicleAllowanceActionPerformed(evt);
            }
        });
        add(TxtVehicleAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator10.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator10.setOpaque(true);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 170, -1));

        TxtMedical.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtMedical.setForeground(new java.awt.Color(31, 58, 147));
        TxtMedical.setBorder(null);
        TxtMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMedicalActionPerformed(evt);
            }
        });
        add(TxtMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 170, 30));

        jSeparator5.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 10, 430));

        jLabelIncentivesAmount1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelIncentivesAmount1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelIncentivesAmount1.setText("Deduction Amount");
        add(jLabelIncentivesAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 220, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 58, 147));
        jLabel9.setText("Insuarance");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 200, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 58, 147));
        jLabel10.setText("Welfare");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 200, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 58, 147));
        jLabel13.setText("Total Deduction");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 200, 30));

        jSeparator16.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator16.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator16.setOpaque(true);
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 140, -1));

        TxtTotalDeducton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtTotalDeducton.setForeground(new java.awt.Color(31, 58, 147));
        TxtTotalDeducton.setBorder(null);
        TxtTotalDeducton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalDeductonActionPerformed(evt);
            }
        });
        add(TxtTotalDeducton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 140, 30));

        jSeparator15.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator15.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator15.setOpaque(true);
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 140, -1));

        TxtInsurance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtInsurance.setForeground(new java.awt.Color(31, 58, 147));
        TxtInsurance.setBorder(null);
        TxtInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtInsuranceActionPerformed(evt);
            }
        });
        add(TxtInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 140, 30));

        jSeparator13.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator13.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator13.setOpaque(true);
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 390, 140, -1));

        TxtWelfare.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtWelfare.setForeground(new java.awt.Color(31, 58, 147));
        TxtWelfare.setBorder(null);
        TxtWelfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWelfareActionPerformed(evt);
            }
        });
        add(TxtWelfare, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 140, 30));

        jSeparator12.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator12.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator12.setOpaque(true);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 140, -1));

        TxtEPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEPF.setForeground(new java.awt.Color(31, 58, 147));
        TxtEPF.setBorder(null);
        TxtEPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEPFActionPerformed(evt);
            }
        });
        add(TxtEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 140, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 58, 147));
        jLabel14.setText("Net Salary");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 200, 30));

        jSeparator17.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator17.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator17.setOpaque(true);
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 200, -1));

        TxtNetSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtNetSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtNetSalary.setBorder(null);
        TxtNetSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNetSalaryActionPerformed(evt);
            }
        });
        add(TxtNetSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 200, 30));

        jLabelAdd.setBackground(new java.awt.Color(34, 49, 63));
        jLabelAdd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdd.setText("Save");
        jLabelAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelAdd.setOpaque(true);
        add(jLabelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 900, 150, 40));

        jLabelCancel.setBackground(new java.awt.Color(34, 49, 63));
        jLabelCancel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("Cancel");
        jLabelCancel.setOpaque(true);
        add(jLabelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 900, 150, 40));

        jSeparator20.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator20.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator20.setOpaque(true);
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 150, -1));

        TxtBasicSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtBasicSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtBasicSalary.setBorder(null);
        TxtBasicSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBasicSalaryActionPerformed(evt);
            }
        });
        add(TxtBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 150, 30));

        DatePickerDate.setForeground(new java.awt.Color(31, 58, 147));
        DatePickerDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        DatePickerDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatePickerDateActionPerformed(evt);
            }
        });
        add(DatePickerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 150, 30));

        jSeparator21.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator21.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator21.setOpaque(true);
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, -1));

        TxtDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDesignation.setForeground(new java.awt.Color(31, 58, 147));
        TxtDesignation.setBorder(null);
        TxtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDesignationActionPerformed(evt);
            }
        });
        TxtDesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDesignationKeyReleased(evt);
            }
        });
        add(TxtDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, 30));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 60, -1));

        TxtEmployeeId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEmployeeId.setForeground(new java.awt.Color(31, 58, 147));
        TxtEmployeeId.setBorder(null);
        TxtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmployeeIdActionPerformed(evt);
            }
        });
        add(TxtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 60, 30));

        jLabelBasicSalary1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary1.setText("Salary Id");
        add(jLabelBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 110, 30));

        jSeparator23.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator23.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator23.setOpaque(true);
        add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 60, -1));

        TxtSalaryId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtSalaryId.setForeground(new java.awt.Color(31, 58, 147));
        TxtSalaryId.setBorder(null);
        TxtSalaryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryIdActionPerformed(evt);
            }
        });
        add(TxtSalaryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 60, 30));

        ButtonPaySlip.setText("Add");
        ButtonPaySlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPaySlipActionPerformed(evt);
            }
        });
        add(ButtonPaySlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 130, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 147));
        jLabel5.setText("Total Incentives");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 200, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 58, 147));
        jLabel11.setText("Over Time Payment");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 200, 30));

        jSeparator14.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator14.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator14.setOpaque(true);
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 170, -1));

        TxtOverTime.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtOverTime.setForeground(new java.awt.Color(31, 58, 147));
        TxtOverTime.setBorder(null);
        TxtOverTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOverTimeActionPerformed(evt);
            }
        });
        add(TxtOverTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 170, 30));

        jSeparator18.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator18.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator18.setOpaque(true);
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, 200, -1));

        TxtGrossSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtGrossSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtGrossSalary.setBorder(null);
        TxtGrossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGrossSalaryActionPerformed(evt);
            }
        });
        add(TxtGrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 200, 30));

        jSeparator19.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator19.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator19.setOpaque(true);
        add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 140, -1));

        TxtLateHoursRate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtLateHoursRate.setForeground(new java.awt.Color(31, 58, 147));
        TxtLateHoursRate.setBorder(null);
        TxtLateHoursRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLateHoursRateActionPerformed(evt);
            }
        });
        add(TxtLateHoursRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 140, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(31, 58, 147));
        jLabel15.setText("Late Hours Rate");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 140, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Further Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 147));
        jLabel8.setText("E.T.F     3%");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(31, 58, 147));
        jLabel17.setText("E.P.F    8%");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(31, 58, 147));
        jLabel18.setText("E.P.F    12%");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        jSeparator25.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator25.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator25.setOpaque(true);
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 80, -1));

        Txtepf.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Txtepf.setForeground(new java.awt.Color(31, 58, 147));
        Txtepf.setBorder(null);
        Txtepf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtepfActionPerformed(evt);
            }
        });
        jPanel1.add(Txtepf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, 30));

        jSeparator26.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator26.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator26.setOpaque(true);
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 80, -1));

        Txtepff.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Txtepff.setForeground(new java.awt.Color(31, 58, 147));
        Txtepff.setBorder(null);
        Txtepff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtepffActionPerformed(evt);
            }
        });
        jPanel1.add(Txtepff, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, 30));

        jSeparator27.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator27.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator27.setOpaque(true);
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, -1));

        TxtETF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtETF.setForeground(new java.awt.Color(31, 58, 147));
        TxtETF.setBorder(null);
        TxtETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtETFActionPerformed(evt);
            }
        });
        jPanel1.add(TxtETF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 250, 160));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(31, 58, 147));
        jLabel16.setText("E.P.F");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 200, 30));

        ButtonAdd1.setText("Pay Slip");
        ButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdd1ActionPerformed(evt);
            }
        });
        add(ButtonAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTotalAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalAllowanceActionPerformed

    private void TxtHouseAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHouseAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHouseAllowanceActionPerformed

    private void TxtVehicleAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVehicleAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVehicleAllowanceActionPerformed

    private void TxtMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMedicalActionPerformed

    private void TxtTotalDeductonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalDeductonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalDeductonActionPerformed

    private void TxtInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtInsuranceActionPerformed

    private void TxtWelfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWelfareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWelfareActionPerformed

    private void TxtEPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEPFActionPerformed

    private void TxtNetSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNetSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNetSalaryActionPerformed

    private void TxtBasicSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBasicSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBasicSalaryActionPerformed

    private void TxtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDesignationActionPerformed

    private void TxtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmployeeIdActionPerformed

    private void TxtSalaryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaryIdActionPerformed

    private void ButtonPaySlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPaySlipActionPerformed
         SalaryDTO salary =new SalaryDTO(
                TxtSalaryId.getText(), 
                TxtEmployeeId.getText(),
                selectDate,
                Double.parseDouble(TxtHouseAllowance.getText()),
                Double.parseDouble(TxtVehicleAllowance.getText()),
                Double.parseDouble(TxtMedical.getText()),
                Double.parseDouble(TxtOverTime.getText()),
                Double.parseDouble(TxtTotalAllowance.getText()),
                Double.parseDouble(TxtEPF.getText()),
                Double.parseDouble(TxtETF.getText()),
                Double.parseDouble(TxtWelfare.getText()),
                Double.parseDouble(TxtInsurance.getText()),
                Double.parseDouble(TxtLateHoursRate.getText()),
                Double.parseDouble(TxtTotalDeducton.getText()),
                Double.parseDouble(TxtGrossSalary.getText()),
                Double.parseDouble(TxtNetSalary.getText()),
                Double.parseDouble(TxtBasicSalary.getText()));
           try {
                
                boolean result = EmployeeSalaryController.addSalary(salary);
                //if(validation()){
                    if (result){
                        JOptionPane.showMessageDialog(this, "Saved successfully");
                     
                        clearTextFields();
                    }else{
                        JOptionPane.showMessageDialog(this, "Failed to Save");
                    }
                //}
            } catch (Exception ex) {
                Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
 
    }//GEN-LAST:event_ButtonPaySlipActionPerformed

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
    employeeName = jComboBoxEmpName.getSelectedItem().toString();
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            ArrayList<AllowanceDTO> allowanceList ;
            if(employee!=null){
                TxtEmployeeId.setText(employee.getId());
                TxtDesignation.setText(employee.getDesignation());
                TxtBasicSalary.setText(""+employee.getSalary());
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed

    private void DatePickerDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickerDateActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        double salary, hraAmt =0.0,vaAmt =0.0,medicalAmt =0.0, totalAllowance = 0.0, epfAmt=0.0, welFareAmt=0.0, insuaranceAmt=0.0, totalDeduction=0.0, othours=0.0, otrate=0.0, LateHrshours=0.0,LateHrsrate=0.0, grossSalary=0.0;
        selectDate = ""+new java.sql.Date( DatePickerDate.getDate().getTime());
        
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
               
            ArrayList<AttendanceDTO> attendanceList = EmployeeAttendanceController.getAttendanceById(employee.getId());
            for(AttendanceDTO attendance : attendanceList){
                othours += attendance.getOThrs();
                LateHrshours += attendance.getLateHrs();
            }
                otrate = employee.getOverTimeHoursRate();
                LateHrsrate = employee.getLateHoursRate();
                
             ArrayList<AllowanceDTO> allowanceList = AllowanceController.getAllowanceByIdAndDate(employee.getId(),selectDate);
               
                for(AllowanceDTO allowance : allowanceList){
                    hraAmt += allowance.getHouserentAllowance();
                    vaAmt += allowance.getVehicleAllowance();
                    medicalAmt += allowance.getMedical();
                    
                }
                totalAllowance = hraAmt+vaAmt+medicalAmt+otrate;
                
               
            ArrayList<DeductionDTO> deductionlist = DeductionController.getDeductionByIdAndDate(employee.getId(),selectDate);
                
                for(DeductionDTO deduction : deductionlist){
                    epfAmt += deduction.getEpf();
                    welFareAmt += deduction.getWelFare();
                    insuaranceAmt += deduction.getInsurance();
                }
                
                totalDeduction = epfAmt+welFareAmt+insuaranceAmt+LateHrsrate;
               
                
                
                TxtHouseAllowance.setText(""+hraAmt);
                TxtVehicleAllowance.setText(""+vaAmt);
                TxtMedical.setText(""+medicalAmt);
                TxtOverTime.setText(""+otrate);
                TxtTotalAllowance.setText(""+totalAllowance);
                
                TxtEPF.setText(""+epfAmt);
                TxtWelfare.setText(""+welFareAmt);
                TxtInsurance.setText(""+insuaranceAmt);
                TxtLateHoursRate.setText(""+LateHrsrate);
                TxtTotalDeducton.setText(""+totalDeduction);
                
                salary=Double.parseDouble(TxtBasicSalary.getText());
                double totalAlow=Double.parseDouble(TxtTotalAllowance.getText());
                double gross = salary + totalAlow;
                TxtGrossSalary.setText(gross+"");
                
                double netSalary= gross-totalDeduction;
                TxtNetSalary.setText(""+netSalary);
                
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DatePickerDateActionPerformed

    private void TxtOverTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOverTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOverTimeActionPerformed

    private void TxtGrossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGrossSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrossSalaryActionPerformed

    private void TxtLateHoursRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLateHoursRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLateHoursRateActionPerformed

    private void TxtDesignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDesignationKeyReleased
        String txt = TxtDesignation.getText();
        int caretPosition = TxtDesignation.getCaretPosition();
        if (!txt.matches("^[A-Za-z//]*$")) {
            TxtDesignation.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtDesignation.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtDesignationKeyReleased

    private void TxtepfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtepfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtepfActionPerformed

    private void TxtepffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtepffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtepffActionPerformed

    private void TxtETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtETFActionPerformed
        
        
    }//GEN-LAST:event_TxtETFActionPerformed

    private void ButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdd1ActionPerformed
//        InputStream input=getClass().getResourceAsStream("/lk/ijse/payroll/report/paySlip.jasper");
//       HashMap map=new HashMap();
//       try {
//            JasperPrint jasperPrint=JasperFillManager.fillReport(input, map,DBConnection.getInstance().getConnection());
//            JasperViewer.viewReport(jasperPrint);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (JRException ex) {
//            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_ButtonAdd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd1;
    private javax.swing.JButton ButtonPaySlip;
    private org.jdesktop.swingx.JXDatePicker DatePickerDate;
    private javax.swing.JTextField TxtBasicSalary;
    private javax.swing.JTextField TxtDesignation;
    private javax.swing.JTextField TxtEPF;
    private javax.swing.JTextField TxtETF;
    private javax.swing.JTextField TxtEmployeeId;
    private javax.swing.JTextField TxtGrossSalary;
    private javax.swing.JTextField TxtHouseAllowance;
    private javax.swing.JTextField TxtInsurance;
    private javax.swing.JTextField TxtLateHoursRate;
    private javax.swing.JTextField TxtMedical;
    private javax.swing.JTextField TxtNetSalary;
    private javax.swing.JTextField TxtOverTime;
    private javax.swing.JTextField TxtSalaryId;
    private javax.swing.JTextField TxtTotalAllowance;
    private javax.swing.JTextField TxtTotalDeducton;
    private javax.swing.JTextField TxtVehicleAllowance;
    private javax.swing.JTextField TxtWelfare;
    private javax.swing.JTextField Txtepf;
    private javax.swing.JTextField Txtepff;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBasicSalary1;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelEmpAtt;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JLabel jLabelIncentivesAmount;
    private javax.swing.JLabel jLabelIncentivesAmount1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables

    private void loadEmployeeName() {
        try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    private double getOvertimertTot(double rate, int hours) {
        System.out.println(""+rate+","+hours);
        double deductionAmt = rate * hours;
        return deductionAmt;
    }
    
    private double getLatehoursTot(double rate, int hours) {
       double deductionAmt = rate * hours;
        return deductionAmt;
    }

   
//    private void clearTextFields() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    private boolean validation() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    private void genarateSalaryId() {
        try {
            String salaryId;
            salaryId = IdGenerater.getNewID("salary", "Id", "S");
            TxtSalaryId.setText(salaryId);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextFields() {
        TxtEmployeeId.setText("");
        TxtDesignation.setText("");
        TxtETF.setText("");
        TxtGrossSalary.setText("");
        TxtHouseAllowance.setText("");
        TxtLateHoursRate.setText("");
        TxtMedical.setText("");
        TxtOverTime.setText("");
        TxtBasicSalary.setText("");
        TxtVehicleAllowance.setText("");
        TxtEPF.setText("");
        TxtTotalAllowance.setText("");
        TxtTotalDeducton.setText("");
        TxtInsurance.setText("");
        TxtWelfare.setText("");
        DatePickerDate.setDate(null);
      
    }

    

}
