/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payroll.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import lk.ijse.payroll.business.custom.EmployeeBO;
import lk.ijse.payroll.business.custom.impl.EmployeeBOImpl;
import lk.ijse.payroll.common.IdGenerater;
import lk.ijse.payroll.controller.AllowanceController;
import lk.ijse.payroll.controller.EmployeeAttendanceController;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.model.AllowanceDTO;
import lk.ijse.payroll.model.AllowanceTblViewDTO;
import lk.ijse.payroll.model.AttendanceDTO;
import lk.ijse.payroll.model.EmployeeDTO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Shashika
 */
public class EmployeeAllowance extends javax.swing.JPanel {
    private String employeeId,date,employeeName;
    private double totalAllowance = 0.0;
    private double salary=0.0;
    private double percentage=0.0;
    private double amount=0.0;
    private double ot = 0.0;
    ButtonGroup bg;
    DefaultTableModel dtm;
    private EmployeeBO employeeBO;

    /**
     * Creates new form Allowance
     */
    public EmployeeAllowance() {
        initComponents();
        commenMethod();
       
       
    }
    public void commenMethod(){
        employeeBO = new EmployeeBOImpl();
        dtm=(DefaultTableModel) TableAllowance.getModel();
        groupButton();
        genarateAllowanceId();
        loadEmployeeNames();
        tableView();
        AutoCompleteDecorator.decorate(jComboBoxEmpName);
        hideTxtField(); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmpAtt = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelEmployeeID = new javax.swing.JLabel();
        jComboBoxEmpName = new javax.swing.JComboBox<>();
        jLabelDesignation = new javax.swing.JLabel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        TxtHRA = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TxtVA = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        TxtMedical = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        TextFieldTotalIncentives = new javax.swing.JTextField();
        jRadioButtonPercentage = new javax.swing.JRadioButton();
        jRadioButtonAmount = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        TxtHRA_percentage = new javax.swing.JTextField();
        SeparatorHRA = new javax.swing.JSeparator();
        SeparatorVA = new javax.swing.JSeparator();
        TxtVA_Percentage = new javax.swing.JTextField();
        SeparatorMedical = new javax.swing.JSeparator();
        TxtMedical_percentage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        TxtSalary = new javax.swing.JTextField();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAllowance = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        DatePickerAllowanceDate = new org.jdesktop.swingx.JXDatePicker();
        jSeparator21 = new javax.swing.JSeparator();
        TxtDesignation = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        TxtEmployeeId = new javax.swing.JTextField();
        jLabelBasicSalary1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        TxtAllowanceId = new javax.swing.JTextField();
        jComboBoxEmpName1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpAtt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        jLabelEmpAtt.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmpAtt.setText(" Allowance");
        add(jLabelEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        jSeparator4.setBackground(new java.awt.Color(210, 215, 211));
        jSeparator4.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jSeparator2.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1630, 10));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1630, -1));

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 110, 30));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 180, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Designation");
        add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 30));

        jLabelBasicSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary.setText("Basic Salary");
        add(jLabelBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 58, 147));
        jLabel1.setText("Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 50, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 147));
        jLabel3.setText("House Rent Allowance");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 200, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 147));
        jLabel4.setText("Vehicle Allowance");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 200, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 147));
        jLabel7.setText("Medical");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 200, 30));

        jSeparator6.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator6.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator6.setOpaque(true);
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 130, -1));

        TxtHRA.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtHRA.setForeground(new java.awt.Color(31, 58, 147));
        TxtHRA.setBorder(null);
        TxtHRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHRAActionPerformed(evt);
            }
        });
        TxtHRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtHRAKeyReleased(evt);
            }
        });
        add(TxtHRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, 30));

        jSeparator7.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator7.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator7.setOpaque(true);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, -1));

        TxtVA.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtVA.setForeground(new java.awt.Color(31, 58, 147));
        TxtVA.setBorder(null);
        TxtVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVAActionPerformed(evt);
            }
        });
        TxtVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtVAKeyReleased(evt);
            }
        });
        add(TxtVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 130, 30));

        jSeparator10.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator10.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator10.setOpaque(true);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 130, -1));

        TxtMedical.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtMedical.setForeground(new java.awt.Color(31, 58, 147));
        TxtMedical.setBorder(null);
        TxtMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMedicalActionPerformed(evt);
            }
        });
        TxtMedical.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtMedicalKeyReleased(evt);
            }
        });
        add(TxtMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 130, 30));

        jSeparator11.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator11.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator11.setOpaque(true);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 130, -1));

        TextFieldTotalIncentives.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TextFieldTotalIncentives.setForeground(new java.awt.Color(31, 58, 147));
        TextFieldTotalIncentives.setBorder(null);
        TextFieldTotalIncentives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTotalIncentivesActionPerformed(evt);
            }
        });
        TextFieldTotalIncentives.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldTotalIncentivesKeyReleased(evt);
            }
        });
        add(TextFieldTotalIncentives, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 130, 30));

        jRadioButtonPercentage.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonPercentage.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jRadioButtonPercentage.setForeground(new java.awt.Color(31, 58, 147));
        jRadioButtonPercentage.setText("Percentage (%)");
        jRadioButtonPercentage.setName(""); // NOI18N
        jRadioButtonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPercentageActionPerformed(evt);
            }
        });
        add(jRadioButtonPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 150, -1));

        jRadioButtonAmount.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAmount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jRadioButtonAmount.setForeground(new java.awt.Color(31, 58, 147));
        jRadioButtonAmount.setText("Amount");
        jRadioButtonAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmountActionPerformed(evt);
            }
        });
        add(jRadioButtonAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, -1));

        jSeparator3.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1660, 20));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 58, 147));
        jLabel9.setText("Update By Salary      :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 30));

        TxtHRA_percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtHRA_percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtHRA_percentage.setBorder(null);
        TxtHRA_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHRA_percentageActionPerformed(evt);
            }
        });
        TxtHRA_percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtHRA_percentageKeyReleased(evt);
            }
        });
        add(TxtHRA_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, 30));

        SeparatorHRA.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorHRA.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorHRA.setOpaque(true);
        add(SeparatorHRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 50, -1));

        SeparatorVA.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorVA.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorVA.setOpaque(true);
        add(SeparatorVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 50, -1));

        TxtVA_Percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtVA_Percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtVA_Percentage.setBorder(null);
        TxtVA_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVA_PercentageActionPerformed(evt);
            }
        });
        TxtVA_Percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtVA_PercentageKeyReleased(evt);
            }
        });
        add(TxtVA_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 50, 30));

        SeparatorMedical.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorMedical.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorMedical.setOpaque(true);
        add(SeparatorMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 50, -1));

        TxtMedical_percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtMedical_percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtMedical_percentage.setBorder(null);
        TxtMedical_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMedical_percentageActionPerformed(evt);
            }
        });
        TxtMedical_percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtMedical_percentageKeyReleased(evt);
            }
        });
        add(TxtMedical_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 50, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 58, 147));
        jLabel11.setText("Total Incentives");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 150, 30));

        jSeparator20.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator20.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator20.setOpaque(true);
        add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 150, -1));

        TxtSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtSalary.setBorder(null);
        TxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryActionPerformed(evt);
            }
        });
        TxtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSalaryKeyReleased(evt);
            }
        });
        add(TxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 150, 30));

        TableAllowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "Name", "Designation", "Salary", "H.R.A", "Vehicle Allowance", "Medical", "Total"
            }
        ));
        jScrollPane2.setViewportView(TableAllowance);

        scrollPane1.add(jScrollPane2);

        add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 580, 250));

        jButton1.setBackground(new java.awt.Color(31, 58, 147));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        BtnSave.setBackground(new java.awt.Color(31, 58, 147));
        BtnSave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        BtnSave.setForeground(new java.awt.Color(255, 255, 255));
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 110, 30));

        DatePickerAllowanceDate.setForeground(new java.awt.Color(31, 58, 147));
        DatePickerAllowanceDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        DatePickerAllowanceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatePickerAllowanceDateActionPerformed(evt);
            }
        });
        add(DatePickerAllowanceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 150, 30));

        jSeparator21.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator21.setOpaque(true);
        add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, -1));

        TxtDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDesignation.setForeground(new java.awt.Color(31, 58, 147));
        TxtDesignation.setBorder(null);
        TxtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDesignationActionPerformed(evt);
            }
        });
        TxtDesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDesignationKeyReleased(evt);
            }
        });
        add(TxtDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, 30));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 70, -1));

        TxtEmployeeId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEmployeeId.setForeground(new java.awt.Color(31, 58, 147));
        TxtEmployeeId.setBorder(null);
        TxtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmployeeIdActionPerformed(evt);
            }
        });
        add(TxtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 70, 20));

        jLabelBasicSalary1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary1.setText("Allowance Id");
        add(jLabelBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 110, 30));

        jSeparator23.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator23.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator23.setOpaque(true);
        add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 50, -1));

        TxtAllowanceId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtAllowanceId.setForeground(new java.awt.Color(31, 58, 147));
        TxtAllowanceId.setBorder(null);
        TxtAllowanceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAllowanceIdActionPerformed(evt);
            }
        });
        add(TxtAllowanceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, 50, 30));

        jComboBoxEmpName1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName1.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpName1ActionPerformed(evt);
            }
        });
        add(jComboBoxEmpName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtHRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHRAActionPerformed
        
        amount = Double.parseDouble(TxtHRA.getText());
        double houseRent = (salary + amount);
        totalAllowance = totalAllowance + houseRent;
        TxtHRA.setText(""+houseRent);
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
        TxtVA.requestFocus();
    }//GEN-LAST:event_TxtHRAActionPerformed

    private void TxtVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVAActionPerformed
        
        amount = Double.parseDouble(TxtVA.getText());
        double vehicleRent = (salary + amount);
        totalAllowance = totalAllowance + vehicleRent;
        TxtVA.setText(""+vehicleRent);
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
        TxtMedical.requestFocus();
    }//GEN-LAST:event_TxtVAActionPerformed

    private void TxtMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMedicalActionPerformed
        
        amount = Double.parseDouble(TxtMedical.getText());
        double medical = (salary + amount);
        totalAllowance = totalAllowance + medical;
        TxtMedical.setText(""+medical);
        
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
        
    }//GEN-LAST:event_TxtMedicalActionPerformed

    private void TextFieldTotalIncentivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTotalIncentivesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextFieldTotalIncentivesActionPerformed

    private void jRadioButtonPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPercentageActionPerformed
        if(jRadioButtonPercentage.isSelected()){
       // TxtHRA_percentage.setEnabled(true);
        //TxtVA_Percentage.setEnabled(true);
       // TxtMedical_percentage.setEnabled(true);
        TxtHRA_percentage.setVisible(true);
        TxtVA_Percentage.setVisible(true);
        TxtMedical_percentage.setVisible(true);
        SeparatorHRA.setVisible(true);
        SeparatorVA.setVisible(true);
        SeparatorMedical.setVisible(true);
        }
        TxtHRA_percentage.requestFocus();
    }//GEN-LAST:event_jRadioButtonPercentageActionPerformed

    private void TxtHRA_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHRA_percentageActionPerformed
        
        salary  = Double.parseDouble(TxtSalary.getText());
        percentage = Double.parseDouble(TxtHRA_percentage.getText());
        double houseRent = (salary * percentage)/100;
        totalAllowance = totalAllowance + houseRent;
        TxtHRA.setText(""+houseRent);
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
        TxtVA_Percentage.requestFocus();
        
    }//GEN-LAST:event_TxtHRA_percentageActionPerformed

    private void TxtVA_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVA_PercentageActionPerformed
        
        salary  = Double.parseDouble(TxtSalary.getText());
        percentage = Double.parseDouble(TxtVA_Percentage.getText());
        double vehicleRent = (salary * percentage)/100;
        totalAllowance = totalAllowance+ vehicleRent;
        TxtVA.setText(""+vehicleRent);
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
        TxtMedical_percentage.requestFocus();
    }//GEN-LAST:event_TxtVA_PercentageActionPerformed

    private void TxtMedical_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMedical_percentageActionPerformed
        
        salary=Double.parseDouble(TxtSalary.getText());
        percentage=Double.parseDouble(TxtMedical_percentage.getText());
        double medical=(salary * percentage)/100;
        totalAllowance=totalAllowance+medical;
        TxtMedical.setText(""+medical);
        TextFieldTotalIncentives.setText(""+totalAllowance);
        
    }//GEN-LAST:event_TxtMedical_percentageActionPerformed

    private void TxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalaryActionPerformed

    private void DatePickerAllowanceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickerAllowanceDateActionPerformed
        date =    ""+ new java.sql.Date(DatePickerAllowanceDate.getDate().getTime());
    }//GEN-LAST:event_DatePickerAllowanceDateActionPerformed

    private void TxtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDesignationActionPerformed

    private void TxtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmployeeIdActionPerformed

    private void TxtAllowanceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAllowanceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAllowanceIdActionPerformed

    private void jRadioButtonAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmountActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonAmount.isSelected()){
        TxtHRA_percentage.setVisible(false);
        TxtVA_Percentage.setVisible(false);
        TxtMedical_percentage.setVisible(false);
        SeparatorHRA.setVisible(false);
        SeparatorVA.setVisible(false);
        SeparatorMedical.setVisible(false);
       }
        TxtHRA.requestFocus();
    }//GEN-LAST:event_jRadioButtonAmountActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        AllowanceDTO allowance = null;
        if(validation()){
            allowance = new AllowanceDTO(
                    TxtAllowanceId.getText(),
                    TxtEmployeeId.getText(),
                    Double.parseDouble(TxtSalary.getText()),
                    date,
                    Double.parseDouble(TxtHRA.getText()),
                    Double.parseDouble(TxtVA.getText()),
                    Double.parseDouble(TxtMedical.getText()),
                    Double.parseDouble(TextFieldTotalIncentives.getText()),'0');
            }else{
             JOptionPane.showMessageDialog(this, "Please fill empty fields");
            }try {
                boolean result = AllowanceController.addAllowance(allowance);
                    if(validation()){
                       if (result){
                        JOptionPane.showMessageDialog(this, "Saved successfully");
                        tableView();
                        clearTextFields();
                        genarateAllowanceId();

                    }else{
                        JOptionPane.showMessageDialog(this, "Failed to Save the Allowance");
                    } 
                    }

                } catch (Exception ex) {
                    Logger.getLogger(EmployeeRegister.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void jComboBoxEmpName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEmpName1ActionPerformed

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            //System.out.println("EMPLOYEE Name >>"+empoyeeName);
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
            
                TxtEmployeeId.setText(employee.getId());
                TxtDesignation.setText(employee.getDesignation());
                TxtSalary.setText(""+employee.getSalary());
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed

    private void TxtDesignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDesignationKeyReleased
        String txt = TxtDesignation.getText();
        int caretPosition = TxtDesignation.getCaretPosition();
        if (!txt.matches("^[A-Za-z//]*$")) {
            TxtDesignation.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtDesignation.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtDesignationKeyReleased

    private void TxtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSalaryKeyReleased
        String txt = TxtSalary.getText();
        int caretPosition = TxtSalary.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtSalary.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtSalary.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtSalaryKeyReleased

    private void TxtHRA_percentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtHRA_percentageKeyReleased
        String txt = TxtHRA_percentage.getText();
        int caretPosition = TxtHRA_percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtHRA_percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtHRA_percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtHRA_percentageKeyReleased

    private void TxtVA_PercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtVA_PercentageKeyReleased
        String txt = TxtVA_Percentage.getText();
        int caretPosition = TxtVA_Percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtVA_Percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtVA_Percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtVA_PercentageKeyReleased

    private void TxtMedical_percentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMedical_percentageKeyReleased
        String txt = TxtMedical_percentage.getText();
        int caretPosition = TxtMedical_percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtMedical_percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtMedical_percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtMedical_percentageKeyReleased

    private void TxtHRAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtHRAKeyReleased
        String txt = TxtHRA.getText();
        int caretPosition = TxtHRA.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtHRA.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtHRA.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtHRAKeyReleased

    private void TxtVAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtVAKeyReleased
        String txt = TxtVA.getText();
        int caretPosition = TxtVA.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtVA.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtVA.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtVAKeyReleased

    private void TxtMedicalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMedicalKeyReleased
        String txt = TxtMedical.getText();
        int caretPosition = TxtMedical.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtMedical.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtMedical.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtMedicalKeyReleased

    private void TextFieldTotalIncentivesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldTotalIncentivesKeyReleased
        String txt = TextFieldTotalIncentives.getText();
        int caretPosition = TextFieldTotalIncentives.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TextFieldTotalIncentives.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TextFieldTotalIncentives.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TextFieldTotalIncentivesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private org.jdesktop.swingx.JXDatePicker DatePickerAllowanceDate;
    private javax.swing.JSeparator SeparatorHRA;
    private javax.swing.JSeparator SeparatorMedical;
    private javax.swing.JSeparator SeparatorVA;
    private org.jdesktop.swingx.JXTable TableAllowance;
    private javax.swing.JTextField TextFieldTotalIncentives;
    private javax.swing.JTextField TxtAllowanceId;
    private javax.swing.JTextField TxtDesignation;
    private javax.swing.JTextField TxtEmployeeId;
    private javax.swing.JTextField TxtHRA;
    private javax.swing.JTextField TxtHRA_percentage;
    private javax.swing.JTextField TxtMedical;
    private javax.swing.JTextField TxtMedical_percentage;
    private javax.swing.JTextField TxtSalary;
    private javax.swing.JTextField TxtVA;
    private javax.swing.JTextField TxtVA_Percentage;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JComboBox<String> jComboBoxEmpName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBasicSalary1;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelEmpAtt;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JRadioButton jRadioButtonAmount;
    private javax.swing.JRadioButton jRadioButtonPercentage;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables

    private void groupButton() {
        bg=new ButtonGroup();
        
        bg.add(jRadioButtonPercentage);
        bg.add(jRadioButtonAmount);
    }

   
    private void genarateAllowanceId() {
        try {
            String allowanceId;
            allowanceId = IdGenerater.getNewID("allowance", "Id", "Al");
            TxtAllowanceId.setText(allowanceId);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadEmployeeNames() {
        try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private boolean validation(){
        if(TxtAllowanceId.getText().equals("") || TxtHRA.getText().equals("") || TxtVA.getText().equals("") || TxtMedical.getText().equals("") || TextFieldTotalIncentives.getText().equals("")){
            return false;
        }else if(TxtAllowanceId.getText()== null || TxtHRA.getText()== null || TxtVA.getText()== null || TxtMedical.getText()== null || TextFieldTotalIncentives.getText()== null ){
            return false;
        }
        return true;
        
    }

    private void clearTextFields() {
        TxtEmployeeId.setText("");
        DatePickerAllowanceDate.setDate(null);
        TxtDesignation.setText("");
        TxtSalary.setText("");
        TxtHRA_percentage.setText("");
        TxtHRA.setText("");
        TxtVA_Percentage.setText("");
        TxtVA.setText("");
        TxtMedical_percentage.setText("");
        TxtMedical.setText("");
        TextFieldTotalIncentives.setText("");
        bg.clearSelection();
        

    }
    
    private void tableView() {
        try {
//          ArrayList<AllowanceDTO> allEmployees= allowanceBO.getAllAllowance();
            ArrayList<AllowanceDTO> allEmployees= AllowanceController.getAllowance();
            dtm = (DefaultTableModel) TableAllowance.getModel();
            dtm.setRowCount(0);
            if(allEmployees==null){return;}
            
                dtm.setRowCount(0);
            for (AllowanceDTO allownce : allEmployees) {

                    Object[] rowData = {
                        allownce.getEmployeeId(),
                        EmployeeRegisterController.searchEmployeeID(allownce.getEmployeeId()).getName(),
                        EmployeeRegisterController.searchEmployeeID(allownce.getEmployeeId()).getDesignation(),
                        EmployeeRegisterController.searchEmployeeID(allownce.getEmployeeId()).getSalary(),
                        allownce.getHouserentAllowance(),
                        allownce.getVehicleAllowance(),
                        allownce.getMedical(),
                        allownce.getTotal()
                    };
                    dtm.addRow(rowData);

            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private void loadEmployeeId() {
//         try {
//            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeIds();
//            for (String employeeName : employeeNames) {
//                ComboBoxId.addItem(employeeName);
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    private double getOtTot(double rate, int hours) {
        double desuctionAmt = rate * hours;
        return desuctionAmt;
    }

    private void hideTxtField() {
        TxtHRA_percentage.setVisible(false);
        SeparatorHRA.setVisible(false);
        TxtVA_Percentage.setVisible(false);
        TxtMedical_percentage.setVisible(false);
        SeparatorVA.setVisible(false);
        SeparatorMedical.setVisible(false);
    }
}

  
   
