/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lk.ijse.payroll.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.payroll.business.custom.EmployeeBO;
import lk.ijse.payroll.business.custom.impl.EmployeeBOImpl;
import lk.ijse.payroll.common.IdGenerater;
import lk.ijse.payroll.controller.DeductionController;
import lk.ijse.payroll.controller.EmployeeRegisterController;
import lk.ijse.payroll.model.DeductionDTO;
import lk.ijse.payroll.model.EmployeeDTO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Shashika
 */
public class EmployeeDeduction extends javax.swing.JPanel {
    private String employeeId="",date="",employeeName;
    private double salary=0.0,percentage=0.0,totalDeduction=0.0,amount=0.0;
    private EmployeeBO employeeBO;
    DefaultTableModel dtm;
    /** Creates new form Incentives */
    public EmployeeDeduction() {
        initComponents();
        commenMethod();
        
    }
    public void commenMethod(){
        employeeBO = new EmployeeBOImpl();
        dtm=(DefaultTableModel) TblDeduction.getModel();
        loadEmployeeId();
        genarateDeductionId();
        groupButton();
        tblView();
        AutoCompleteDecorator.decorate(jComboBoxEmpName);
        hideTxtField();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelEmpAtt = new javax.swing.JLabel();
        jLabelEmployeeID = new javax.swing.JLabel();
        jLabelDesignation = new javax.swing.JLabel();
        jLabelEmployeeName = new javax.swing.JLabel();
        jLabelBasicSalary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        SeparatorInsurance = new javax.swing.JSeparator();
        TxtInsuarance_Percentage = new javax.swing.JTextField();
        SeparatorWelfare = new javax.swing.JSeparator();
        TxtWelfare_Percentage = new javax.swing.JTextField();
        TxtEPF_percentage = new javax.swing.JTextField();
        SeparatorEPF = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        TxtEPF = new javax.swing.JTextField();
        TxtWelFare = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        TxtInsuarance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtTotalDeduction = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        TxtSalary = new javax.swing.JTextField();
        DatePickerDate = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        ButtonSave = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        TxtDesignation = new javax.swing.JTextField();
        TxtDeductionId = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelBasicSalary1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDeduction = new org.jdesktop.swingx.JXTable();
        jRadioButtonPercentage = new javax.swing.JRadioButton();
        jRadioButtonAmount = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        TxtEmployeeId = new javax.swing.JTextField();
        jComboBoxEmpName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator1.setDoubleBuffered(true);
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1630, -1));

        jSeparator2.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1630, 10));

        jSeparator4.setBackground(new java.awt.Color(210, 215, 211));
        jSeparator4.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setOpaque(true);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jLabelEmpAtt.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        jLabelEmpAtt.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmpAtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payroll/asset/icons8_Minus_30px_1.png"))); // NOI18N
        jLabelEmpAtt.setText(" Deduction");
        add(jLabelEmpAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        jLabelEmployeeID.setBackground(new java.awt.Color(1, 50, 67));
        jLabelEmployeeID.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeID.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeID.setText("Employee ID");
        add(jLabelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, 30));

        jLabelDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelDesignation.setForeground(new java.awt.Color(31, 58, 147));
        jLabelDesignation.setText("Designation");
        add(jLabelDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 30));

        jLabelEmployeeName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelEmployeeName.setForeground(new java.awt.Color(31, 58, 147));
        jLabelEmployeeName.setText("Employee Name");
        add(jLabelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 30));

        jLabelBasicSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary.setText("Basic Salary");
        add(jLabelBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 110, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 58, 147));
        jLabel1.setText("Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 50, 30));

        jSeparator3.setForeground(new java.awt.Color(31, 58, 147));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1660, 20));

        SeparatorInsurance.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorInsurance.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorInsurance.setOpaque(true);
        add(SeparatorInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 50, -1));

        TxtInsuarance_Percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtInsuarance_Percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtInsuarance_Percentage.setBorder(null);
        TxtInsuarance_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtInsuarance_PercentageActionPerformed(evt);
            }
        });
        TxtInsuarance_Percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtInsuarance_PercentageKeyReleased(evt);
            }
        });
        add(TxtInsuarance_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 50, 30));

        SeparatorWelfare.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorWelfare.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorWelfare.setOpaque(true);
        add(SeparatorWelfare, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 50, -1));

        TxtWelfare_Percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtWelfare_Percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtWelfare_Percentage.setBorder(null);
        TxtWelfare_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWelfare_PercentageActionPerformed(evt);
            }
        });
        TxtWelfare_Percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtWelfare_PercentageKeyReleased(evt);
            }
        });
        add(TxtWelfare_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 50, 30));

        TxtEPF_percentage.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEPF_percentage.setForeground(new java.awt.Color(31, 58, 147));
        TxtEPF_percentage.setBorder(null);
        TxtEPF_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEPF_percentageActionPerformed(evt);
            }
        });
        TxtEPF_percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEPF_percentageKeyReleased(evt);
            }
        });
        add(TxtEPF_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 50, 30));

        SeparatorEPF.setBackground(new java.awt.Color(31, 58, 147));
        SeparatorEPF.setForeground(new java.awt.Color(31, 58, 147));
        SeparatorEPF.setOpaque(true);
        add(SeparatorEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 50, -1));

        jSeparator6.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator6.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator6.setOpaque(true);
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 150, -1));

        TxtEPF.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEPF.setForeground(new java.awt.Color(31, 58, 147));
        TxtEPF.setBorder(null);
        TxtEPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEPFActionPerformed(evt);
            }
        });
        TxtEPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEPFKeyReleased(evt);
            }
        });
        add(TxtEPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 150, 30));

        TxtWelFare.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtWelFare.setForeground(new java.awt.Color(31, 58, 147));
        TxtWelFare.setBorder(null);
        TxtWelFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWelFareActionPerformed(evt);
            }
        });
        TxtWelFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtWelFareKeyReleased(evt);
            }
        });
        add(TxtWelFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 150, 30));

        jSeparator7.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator7.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator7.setOpaque(true);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 150, -1));

        jSeparator9.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator9.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator9.setOpaque(true);
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 150, -1));

        TxtInsuarance.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtInsuarance.setForeground(new java.awt.Color(31, 58, 147));
        TxtInsuarance.setBorder(null);
        TxtInsuarance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtInsuaranceActionPerformed(evt);
            }
        });
        TxtInsuarance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtInsuaranceKeyReleased(evt);
            }
        });
        add(TxtInsuarance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 150, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 58, 147));
        jLabel11.setText("Total Deduction");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 150, 30));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 147));
        jLabel8.setText("E.P.F      (8%)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 160, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(31, 58, 147));
        jLabel12.setText("Welfare");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 58, 147));
        jLabel14.setText("Insuarance");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 160, 30));

        TxtTotalDeduction.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtTotalDeduction.setForeground(new java.awt.Color(31, 58, 147));
        TxtTotalDeduction.setBorder(null);
        TxtTotalDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalDeductionActionPerformed(evt);
            }
        });
        TxtTotalDeduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtTotalDeductionKeyReleased(evt);
            }
        });
        add(TxtTotalDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 150, 30));

        jSeparator10.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator10.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator10.setOpaque(true);
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 150, -1));

        jSeparator11.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator11.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator11.setOpaque(true);
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 150, -1));

        TxtSalary.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtSalary.setForeground(new java.awt.Color(31, 58, 147));
        TxtSalary.setBorder(null);
        TxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalaryActionPerformed(evt);
            }
        });
        TxtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSalaryKeyReleased(evt);
            }
        });
        add(TxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 150, 30));

        DatePickerDate.setForeground(new java.awt.Color(31, 58, 147));
        DatePickerDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        DatePickerDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatePickerDateActionPerformed(evt);
            }
        });
        add(DatePickerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 160, 30));

        jButton1.setBackground(new java.awt.Color(31, 58, 147));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 90, 30));

        ButtonSave.setBackground(new java.awt.Color(31, 58, 147));
        ButtonSave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        ButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });
        add(ButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 90, 30));

        jSeparator12.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator12.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator12.setOpaque(true);
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));

        TxtDesignation.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDesignation.setForeground(new java.awt.Color(31, 58, 147));
        TxtDesignation.setBorder(null);
        TxtDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDesignationActionPerformed(evt);
            }
        });
        TxtDesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDesignationKeyReleased(evt);
            }
        });
        add(TxtDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 30));

        TxtDeductionId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtDeductionId.setForeground(new java.awt.Color(31, 58, 147));
        TxtDeductionId.setBorder(null);
        TxtDeductionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDeductionIdActionPerformed(evt);
            }
        });
        add(TxtDeductionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 50, 30));

        jSeparator14.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator14.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator14.setOpaque(true);
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 50, -1));

        jLabelBasicSalary1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelBasicSalary1.setForeground(new java.awt.Color(31, 58, 147));
        jLabelBasicSalary1.setText("Deduction Id");
        add(jLabelBasicSalary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 110, 30));

        TblDeduction.setForeground(new java.awt.Color(31, 58, 147));
        TblDeduction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "Name", "Deduction", "Basic", "E.P.F", "Welfare", "Insuarance", "Date", "Total"
            }
        ));
        jScrollPane2.setViewportView(TblDeduction);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 630, 210));

        jRadioButtonPercentage.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonPercentage.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jRadioButtonPercentage.setForeground(new java.awt.Color(31, 58, 147));
        jRadioButtonPercentage.setText("Percentage (%)");
        jRadioButtonPercentage.setName(""); // NOI18N
        jRadioButtonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPercentageActionPerformed(evt);
            }
        });
        add(jRadioButtonPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, -1));

        jRadioButtonAmount.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonAmount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jRadioButtonAmount.setForeground(new java.awt.Color(31, 58, 147));
        jRadioButtonAmount.setText("Amount");
        jRadioButtonAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmountActionPerformed(evt);
            }
        });
        add(jRadioButtonAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 100, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 58, 147));
        jLabel9.setText("Update By Salary   :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 30));

        jSeparator22.setBackground(new java.awt.Color(31, 58, 147));
        jSeparator22.setForeground(new java.awt.Color(31, 58, 147));
        jSeparator22.setOpaque(true);
        add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 70, -1));

        TxtEmployeeId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        TxtEmployeeId.setForeground(new java.awt.Color(31, 58, 147));
        TxtEmployeeId.setBorder(null);
        TxtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmployeeIdActionPerformed(evt);
            }
        });
        add(TxtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 70, 20));

        jComboBoxEmpName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jComboBoxEmpName.setForeground(new java.awt.Color(31, 58, 147));
        jComboBoxEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpNameActionPerformed(evt);
            }
        });
        add(jComboBoxEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtInsuarance_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtInsuarance_PercentageActionPerformed
        salary=Double.parseDouble(TxtSalary.getText());
        percentage=Double.parseDouble(TxtInsuarance_Percentage.getText());
        double insuarance=(salary * percentage)/100;
        totalDeduction=totalDeduction+insuarance;
        TxtInsuarance.setText(""+insuarance);
        TxtTotalDeduction.setText(""+totalDeduction);
    }//GEN-LAST:event_TxtInsuarance_PercentageActionPerformed

    private void TxtWelfare_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWelfare_PercentageActionPerformed
        salary=Double.parseDouble(TxtSalary.getText());
        percentage=Double.parseDouble(TxtWelfare_Percentage.getText());
        double welFare=(salary * percentage)/100;
        totalDeduction=totalDeduction+welFare;
        TxtWelFare.setText(""+welFare);
        TxtTotalDeduction.setText(""+totalDeduction);
        
        TxtInsuarance_Percentage.requestFocus();
    }//GEN-LAST:event_TxtWelfare_PercentageActionPerformed

    private void TxtEPF_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEPF_percentageActionPerformed
        salary=Double.parseDouble(TxtSalary.getText());
        percentage=Double.parseDouble(TxtEPF_percentage.getText());
        double EPF=(salary * percentage)/100;
        totalDeduction=totalDeduction+EPF;
        TxtEPF.setText(""+EPF);
        TxtTotalDeduction.setText(""+totalDeduction);
        
        TxtWelfare_Percentage.requestFocus();
    }//GEN-LAST:event_TxtEPF_percentageActionPerformed

    private void TxtEPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEPFActionPerformed
        amount = Double.parseDouble(TxtEPF.getText());
        double EPF = amount;
        totalDeduction = totalDeduction + EPF;
        TxtEPF.setText(""+EPF);
        TxtTotalDeduction.setText(""+totalDeduction);
        
        TxtWelFare.requestFocus();
    }//GEN-LAST:event_TxtEPFActionPerformed

    private void TxtWelFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWelFareActionPerformed
        amount = Double.parseDouble(TxtWelFare.getText());
        double welFare =  amount;
        totalDeduction = totalDeduction + welFare;
        TxtWelFare.setText(""+welFare);
        TxtTotalDeduction.setText(""+totalDeduction);
        
        TxtInsuarance.requestFocus();
    }//GEN-LAST:event_TxtWelFareActionPerformed

    private void TxtInsuaranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtInsuaranceActionPerformed
        amount = Double.parseDouble(TxtInsuarance.getText());
        double insuarance = amount;
        totalDeduction = totalDeduction + insuarance;
        TxtInsuarance.setText(""+insuarance);
        TxtTotalDeduction.setText(""+totalDeduction);
    }//GEN-LAST:event_TxtInsuaranceActionPerformed

    private void TxtTotalDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalDeductionActionPerformed
        
    }//GEN-LAST:event_TxtTotalDeductionActionPerformed

    private void TxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalaryActionPerformed
        
    }//GEN-LAST:event_TxtSalaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        DeductionDTO deduction = null;
        if(validation()){
            deduction = new DeductionDTO(
                    TxtDeductionId.getText(),
                    TxtEmployeeId.getText(),
                    Double.parseDouble(TxtSalary.getText()),
                    date,
                    Double.parseDouble(TxtEPF.getText()),
                    Double.parseDouble(TxtWelFare.getText()),
                    Double.parseDouble(TxtInsuarance.getText()),
                    Double.parseDouble(TxtTotalDeduction.getText()),'0');
            }else{
             JOptionPane.showMessageDialog(this, "Please fill empty fields");
            }try {
                boolean result = DeductionController.addDeduction(deduction);
                    if(validation()){
                       if (result){
                        JOptionPane.showMessageDialog(this, "Saved successfully");
                        //clearTextFields();
                        tblView(); 

                    }else{
                        JOptionPane.showMessageDialog(this, "Failed to Save the Deduction");
                    } 
                    }

                } catch (Exception ex) {
                    Logger.getLogger(EmployeeRegister.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void TxtDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDesignationActionPerformed

    private void DatePickerDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickerDateActionPerformed
        date = ""+ new java.sql.Date(DatePickerDate.getDate().getTime());
    }//GEN-LAST:event_DatePickerDateActionPerformed

    private void TxtDeductionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDeductionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDeductionIdActionPerformed

    private void jRadioButtonPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPercentageActionPerformed
        if(jRadioButtonPercentage.isSelected()){
            TxtEPF_percentage.setVisible(true);
            TxtWelfare_Percentage.setVisible(true);
            TxtInsuarance_Percentage.setVisible(true);
            SeparatorEPF.setVisible(true);
            SeparatorWelfare.setVisible(true);
            SeparatorInsurance.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonPercentageActionPerformed

    private void jRadioButtonAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmountActionPerformed
        
        if(jRadioButtonAmount.isSelected()){
            TxtEPF_percentage.setVisible(false);
            TxtWelfare_Percentage.setVisible(false);
            TxtInsuarance_Percentage.setVisible(false);
            SeparatorEPF.setVisible(false);
            SeparatorWelfare.setVisible(false);
            SeparatorInsurance.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButtonAmountActionPerformed

    private void TxtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmployeeIdActionPerformed

    private void jComboBoxEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpNameActionPerformed
        employeeName = jComboBoxEmpName.getSelectedItem().toString();
        try {
            String empoyeeName=(String) jComboBoxEmpName.getSelectedItem();
            EmployeeDTO employee=EmployeeRegisterController.searchEmployee(empoyeeName);
            if(employee!=null){
                
                TxtEmployeeId.setText(employee.getId());
                TxtDesignation.setText(employee.getDesignation());
                TxtSalary.setText(""+employee.getSalary());
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAllowance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxEmpNameActionPerformed

    private void TxtDesignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDesignationKeyReleased
        String txt = TxtDesignation.getText();
        int caretPosition = TxtDesignation.getCaretPosition();
        if (!txt.matches("^[A-Za-z//]*$")) {
            TxtDesignation.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtDesignation.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtDesignationKeyReleased

    private void TxtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSalaryKeyReleased
        String txt = TxtSalary.getText();
        int caretPosition = TxtSalary.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtSalary.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtSalary.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtSalaryKeyReleased

    private void TxtEPF_percentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEPF_percentageKeyReleased
        String txt = TxtEPF_percentage.getText();
        int caretPosition = TxtEPF_percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtEPF_percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtEPF_percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtEPF_percentageKeyReleased

    private void TxtWelfare_PercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtWelfare_PercentageKeyReleased
        String txt = TxtWelfare_Percentage.getText();
        int caretPosition = TxtWelfare_Percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtWelfare_Percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtWelfare_Percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtWelfare_PercentageKeyReleased

    private void TxtInsuarance_PercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtInsuarance_PercentageKeyReleased
        String txt = TxtInsuarance_Percentage.getText();
        int caretPosition = TxtInsuarance_Percentage.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtInsuarance_Percentage.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtInsuarance_Percentage.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtInsuarance_PercentageKeyReleased

    private void TxtEPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEPFKeyReleased
        String txt = TxtEPF.getText();
        int caretPosition = TxtEPF.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtEPF.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtEPF.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtEPFKeyReleased

    private void TxtWelFareKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtWelFareKeyReleased
        String txt = TxtWelFare.getText();
        int caretPosition = TxtWelFare.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtWelFare.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtWelFare.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtWelFareKeyReleased

    private void TxtInsuaranceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtInsuaranceKeyReleased
        String txt = TxtInsuarance.getText();
        int caretPosition = TxtInsuarance.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtInsuarance.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtInsuarance.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtInsuaranceKeyReleased

    private void TxtTotalDeductionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTotalDeductionKeyReleased
        String txt = TxtTotalDeduction.getText();
        int caretPosition = TxtTotalDeduction.getCaretPosition();
        if (!txt.matches("^[\\d]*")) {
            TxtTotalDeduction.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            TxtTotalDeduction.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_TxtTotalDeductionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSave;
    private org.jdesktop.swingx.JXDatePicker DatePickerDate;
    private javax.swing.JSeparator SeparatorEPF;
    private javax.swing.JSeparator SeparatorInsurance;
    private javax.swing.JSeparator SeparatorWelfare;
    private org.jdesktop.swingx.JXTable TblDeduction;
    private javax.swing.JTextField TxtDeductionId;
    private javax.swing.JTextField TxtDesignation;
    private javax.swing.JTextField TxtEPF;
    private javax.swing.JTextField TxtEPF_percentage;
    private javax.swing.JTextField TxtEmployeeId;
    private javax.swing.JTextField TxtInsuarance;
    private javax.swing.JTextField TxtInsuarance_Percentage;
    private javax.swing.JTextField TxtSalary;
    private javax.swing.JTextField TxtTotalDeduction;
    private javax.swing.JTextField TxtWelFare;
    private javax.swing.JTextField TxtWelfare_Percentage;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEmpName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelBasicSalary1;
    private javax.swing.JLabel jLabelDesignation;
    private javax.swing.JLabel jLabelEmpAtt;
    private javax.swing.JLabel jLabelEmployeeID;
    private javax.swing.JLabel jLabelEmployeeName;
    private javax.swing.JRadioButton jRadioButtonAmount;
    private javax.swing.JRadioButton jRadioButtonPercentage;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables

    private void groupButton() {
        ButtonGroup bg=new ButtonGroup();
        
        bg.add(jRadioButtonPercentage);
        bg.add(jRadioButtonAmount);
        
    }

    private void loadEmployeeId() {
        try {
            ArrayList<String>employeeNames=EmployeeRegisterController.getAllEmployeeNames();
            for (String employeeName : employeeNames) {
                jComboBoxEmpName.addItem(employeeName);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void genarateDeductionId() {
         try {
            String deductionId;
            deductionId = IdGenerater.getNewID("Deduction", "ID", "D");
            TxtDeductionId.setText(deductionId);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeDeduction.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeDeduction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validation(){
        if(TxtDeductionId.getText().equals("") || TxtEPF.getText().equals("") || TxtWelFare.getText().equals("") || TxtInsuarance.getText().equals("") || TxtTotalDeduction.getText().equals("")){
            return false;
        }else if(TxtDeductionId.getText()== null || TxtEPF.getText()== null || TxtWelFare.getText()== null || TxtInsuarance.getText()== null || TxtTotalDeduction.getText()== null ){
            return false;
        }
        return true;
    }

    private void tblView() {
        try {

            ArrayList<DeductionDTO> allDeductions= DeductionController.getAllowance();
            dtm = (DefaultTableModel) TblDeduction.getModel();
            dtm.setRowCount(0);
            if(allDeductions==null){return;}
            
                dtm.setRowCount(0);
            for (DeductionDTO deduction : allDeductions) {

                    Object[] rowData = {
                        deduction.getEmployeeId(),
                        EmployeeRegisterController.searchEmployeeID(deduction.getEmployeeId()).getName(),
                        EmployeeRegisterController.searchEmployeeID(deduction.getEmployeeId()).getDesignation(),
                        EmployeeRegisterController.searchEmployeeID(deduction.getEmployeeId()).getSalary(),
                        deduction.getEpf(),
                        deduction.getWelFare(),
                        deduction.getInsurance(),
                        deduction.getDate(),
                        deduction.getTotal()
                    };
                    dtm.addRow(rowData);

            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private double getLhTot(double rate, int hours) {
        double desuctionAmt = rate * hours;
        return desuctionAmt;
    }

    private void hideTxtField() {
        TxtEPF_percentage.setVisible(false);
        TxtWelfare_Percentage.setVisible(false);
        TxtInsuarance_Percentage.setVisible(false);
        SeparatorEPF.setVisible(false);
        SeparatorWelfare.setVisible(false);
        SeparatorInsurance.setVisible(false);
        
    }

}
