/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payroll.view;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Chamil
 */
public class Login extends javax.swing.JFrame {
private String Uname,Pwd;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        UserNameTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PasswordTxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogInBtn = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        ForgetBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Niyagama"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gurugodella Tea Factory (Pvt) Ltd "); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        jPanel2.setBackground(new java.awt.Color(98, 0, 234));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(101, 31, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 270, -1));

        UserNameTxt.setBackground(new java.awt.Color(101, 31, 255));
        UserNameTxt.setBorder(null);
        UserNameTxt.setOpaque(false);
        UserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtActionPerformed(evt);
            }
        });
        jPanel3.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 270, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 208, 270, -1));

        PasswordTxt.setBackground(new java.awt.Color(101, 31, 255));
        PasswordTxt.setBorder(null);
        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });
        jPanel3.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 270, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, 20));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 60, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payroll/asset/icons8_Password_30px.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payroll/asset/icons8_User_30px.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        LogInBtn.setBackground(new java.awt.Color(179, 136, 255));
        LogInBtn.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInBtn.setText("Log in");
        LogInBtn.setOpaque(true);
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInBtnMouseClicked(evt);
            }
        });
        jPanel3.add(LogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 270, 30));

        jCheckBox1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("KEEP ME LOGGED IN");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 20));

        ForgetBtn.setBackground(new java.awt.Color(101, 31, 255));
        ForgetBtn.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        ForgetBtn.setForeground(new java.awt.Color(255, 255, 255));
        ForgetBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgetBtn.setText("Forget Password ?");
        ForgetBtn.setOpaque(true);
        ForgetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgetBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgetBtnMouseEntered(evt);
            }
        });
        jPanel3.add(ForgetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 410, 370));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ForgetBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetBtnMouseEntered
         ForgetBtn.setBackground(new java.awt.Color(179, 157, 219));
    }//GEN-LAST:event_ForgetBtnMouseEntered

    private void ForgetBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetBtnMouseExited
       ForgetBtn.setBackground(new java.awt.Color(101,31,255));
    }//GEN-LAST:event_ForgetBtnMouseExited

    private void LogInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseClicked
        //Home home=new Home();
        Uname = UserNameTxt.getText();
        Pwd   = PasswordTxt.getText();
        if(!(Uname.equals("") || Pwd.equals(""))){
            
            if(Uname.equals("shashika") && Pwd.equals("123")){
                // JOptionPane.showMessageDialog(this, "Login Successfully");
                 new Home().setVisible(true);
                 this.dispose();
            }else{
               JOptionPane.showMessageDialog(this, "Please enter correct Username and Password"); 
               clearFields();
            }
            
        }else{
               clearFields();
            JOptionPane.showMessageDialog(this, "Please fill empty fields"); 
        }
       
        
    }//GEN-LAST:event_LogInBtnMouseClicked

    private void UserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtActionPerformed
        PasswordTxt.requestFocus();
    }//GEN-LAST:event_UserNameTxtActionPerformed

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
        LogInBtn.requestFocus();
    }//GEN-LAST:event_PasswordTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetBtn;
    private javax.swing.JLabel LogInBtn;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
       UserNameTxt.setText("");
       PasswordTxt.setText("");
    }
}
