/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payroll.view;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.payroll.dbconnection.DBConnection;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Chamil
 */
public class Reports extends javax.swing.JPanel {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEmployeeDetails = new javax.swing.JButton();
        BtnAttendance = new javax.swing.JButton();
        BtnDeduction = new javax.swing.JButton();
        BtnAllowance = new javax.swing.JButton();
        BtnOt = new javax.swing.JButton();
        BtnLt = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1156, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEmployeeDetails.setText("EmployeeDetails");
        BtnEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmployeeDetailsActionPerformed(evt);
            }
        });
        add(BtnEmployeeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 30));

        BtnAttendance.setText("Attendance");
        BtnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAttendanceActionPerformed(evt);
            }
        });
        add(BtnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 30));

        BtnDeduction.setText("Deduction");
        BtnDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeductionActionPerformed(evt);
            }
        });
        add(BtnDeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 123, 110, 30));

        BtnAllowance.setText("Allowance");
        BtnAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllowanceActionPerformed(evt);
            }
        });
        add(BtnAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 123, 110, 30));

        BtnOt.setText("Ot Hours");
        BtnOt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOtActionPerformed(evt);
            }
        });
        add(BtnOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 173, 130, 30));

        BtnLt.setText("Late Hours");
        BtnLt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLtActionPerformed(evt);
            }
        });
        add(BtnLt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 173, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmployeeDetailsActionPerformed
      
       InputStream input=getClass().getResourceAsStream("/lk/ijse/payroll/report/employeeDetails.jasper");
       HashMap map=new HashMap();
       try {
            JasperPrint jasperPrint=JasperFillManager.fillReport(input, map,DBConnection.getInstance().getConnection());
            JasperViewer.viewReport(jasperPrint);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(EmployeeSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEmployeeDetailsActionPerformed

    private void BtnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAttendanceActionPerformed
       AttendanceReport attendanceReport=new AttendanceReport();
       attendanceReport.setVisible(true);
    }//GEN-LAST:event_BtnAttendanceActionPerformed

    private void BtnDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeductionActionPerformed
       DeductionReport deductionReport=new DeductionReport();
       deductionReport.setVisible(true);
    }//GEN-LAST:event_BtnDeductionActionPerformed

    private void BtnAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllowanceActionPerformed
       AllowanceReport allowanceReport=new AllowanceReport();
       allowanceReport.setVisible(true);
    }//GEN-LAST:event_BtnAllowanceActionPerformed

    private void BtnOtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOtActionPerformed
       OtHoursReport otHoursReport=new OtHoursReport();
       otHoursReport.setVisible(true);
    }//GEN-LAST:event_BtnOtActionPerformed

    private void BtnLtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLtActionPerformed
        LatehoursReport latehoursReport=new LatehoursReport();
        latehoursReport.setVisible(true);
    }//GEN-LAST:event_BtnLtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAllowance;
    private javax.swing.JButton BtnAttendance;
    private javax.swing.JButton BtnDeduction;
    private javax.swing.JButton BtnEmployeeDetails;
    private javax.swing.JButton BtnLt;
    private javax.swing.JButton BtnOt;
    // End of variables declaration//GEN-END:variables
}
